### ISSUE TITLE
generating Viewmodel from derived model

### ISSUE THREAD

**Issue by khaledafifi** [thomasclaudiushuber/mvvmgen#16]
class A
{
	string id{get; set;}
	string Name{get; set;}
}

class B : A
{
	string Email {get; set; }
}

the generated ViewModel from B must include props from A but it  doesn't.

**Comment by thomasclaudiushuber** [comment]
Hi @khaledafifi , sorry, I was on holidays.

You're missing the public access modifier here. private members are not visible in subclasses. Should be

```
class A : MvvmGen.ViewModel.ViewModelBase
{
public string id{get; set;}
public string Name{get; set;}
}

class B : A
{
public string Email {get; set; }
}
```

**Comment by khaledafifi** [comment]
the same result .. the generated vm publish prosperities only from the derived class not the base.
please try yourself.
thanks to your great project.

**Comment by thomasclaudiushuber** [comment]
Ok, reproduced. You're using the ModelType property of the attribute I guess to generate a ViewModel from a Model.

So, for the code below, the `MyViewModel` should have the properties `Name` and `Email`, but it has only an `Email` property.

```
public class BaseType
{
    public string Name { get; set; }
}

public class SubType : BaseType
{
    public string Email { get; set; }
}

[ViewModel(ModelType = typeof(SubType))]
public partial class MyViewModel
{

}
```

**Comment by thomasclaudiushuber** [comment]
Thank you @khaledafifi for the issue. It's fixed and it will be part of an upcoming release.
