### ISSUE TITLE
ViewModelBase must be fully qualified

### ISSUE THREAD

**Issue by SeidChr** [thomasclaudiushuber/mvvmgen#17]
I've had build issues with the generated code out of the box, because we have a "ViewModelBase" class in the very same namespace. 
Please qualify the referenced ViewModelBase class in generated code, and/or make the base-class configurable in the [ViewModel] attribute.

**Comment by thomasclaudiushuber** [comment]
Thanks @SeidChr. Your PR is merged and the new NuGet package with version 1.1.2 is available on NuGet.

Have a great day!
