### ISSUE TITLE
PropertyInvalidate on readonly properties do not generate OnPropertyChanged in properties generated from a model.

### ISSUE THREAD

**Issue by erikhermansson79** [thomasclaudiushuber/mvvmgen#20]
```
public class Model
{
    public int Value { get; set; }
}

[ViewModel(typeof(Model))]
public partial class ViewModel
{
    [PropertyInvalidate(nameof(Value))]
    public int ComputedValue => this.Value * 5;
}
```

I expect the generated property `ViewModel.Value` to have `OnPropertyChanged("ComputedValue")` but it doesn't.

**Comment by thomasclaudiushuber** [comment]
Thanks @erikhermansson79 ,

yes, you're absolutely right, it should also be included in the generated model property. 
That's a bug, I'll look into this one.

**Comment by thomasclaudiushuber** [comment]
Thank you @erikhermansson79. This bug was fixed and the fix will be part of the next MvvmGen release.
