### ISSUE TITLE
CommandInvalidate with "morePropertyNames" only works for "propertyName"

### ISSUE THREAD

**Issue by TopperDEL** [thomasclaudiushuber/mvvmgen#21]
The other properties do not invalidate the CanExecute-Method.

**Comment by thomasclaudiushuber** [comment]
Thanks @TopperDEL, I'll try to reproduce this in January. If you have a project ready that shows the issue, that would be helpful and save a bit of time for me. If not, that's fine too.

**Comment by TopperDEL** [comment]
I had this coding:

```
[Property] private bool _work;
[Property] private bool _homework;
[Property] private bool _garden;
[Property] private bool _children;
[Property] private bool _school;
[Property] private bool _study;
[Property] private bool _hobby;
[Property] private bool _leisure;
[Property] private bool _sport;
[Property] private bool _own1;
[Property] private bool _own2;
[Property] private bool _own3;
[Property] private string _own1Title;
[Property] private string _own2Title;
[Property] private string _own3Title;

[CommandInvalidate(nameof(Work), new string[] { nameof(Homework), nameof(Garden), nameof(Children), nameof(School), nameof(Study), nameof(Hobby), nameof(Leisure), nameof(Sport), nameof(Own1), nameof(Own1Title), nameof(Own2), nameof(Own2Title), nameof(Own3), nameof(Own3Title) })]
[Command(CanExecuteMethod = nameof(CanSave))]
private void Save()
{
}

private bool CanSave()
{
     return Work || Homework || Garden || Children || School || Study || Hobby || Leisure || Sport ||
                   (Own1 && !string.IsNullOrEmpty(Own1Title)) ||
                   (Own2 && !string.IsNullOrEmpty(Own2Title)) ||
                   (Own3 && !string.IsNullOrEmpty(Own3Title));
}
```

**Comment by thomasclaudiushuber** [comment]
Thanks @TopperDEL, that helps a lot. I'll try to reproduce this bug next weekend. 

I think it's caused because of the use of the explicit "new string[]{}". As the params keyword is defined on the attribute, I expected it to be used like this:
```
[CommandInvalidate(nameof(Work), nameof(Homework), nameof(Garden),...)]
```
And that is what is covered by the unit tests. But don't get me wrong, 
```
[CommandInvalidate(nameof(Work), new string[]{ nameof(Homework), nameof(Garden),... } )]
```
should work too. But as the code gen runs at a low level, I'm sure I need to do something in addition for this.

Thank you, great find!

**Comment by TopperDEL** [comment]
Ah, thanks! I can confirm it works by using the proposed way (a simple list of nameof(), nameof()...). I'm not sure why I did not use that one. 

So maybe it lasts to put a small info in the docs about this. It's not the most used feature, I guess.

By the way: I love MVVMGen - awesome how simple yet effective it is!

**Comment by thomasclaudiushuber** [comment]
Thank you @TopperDEL for the issue. It's fixed and it will be part of an upcoming release.
