### ISSUE TITLE
Invalidate Readonly Model Property in ViewModel

### ISSUE THREAD

**Issue by ideonella** [thomasclaudiushuber/mvvmgen#42]
This could be me not understanding how to use the library. Anyway, here is the simplest example of what I have.
```
  public class MyModel
  {
    private const string path = @"CppLib.dll";
    private readonly IntPtr _class;

    [DllImport(path, CallingConvention = CallingConvention.Cdecl)]
    private static extern uint GetNumber(IntPtr _class);

    public uint Number { get { return GetNumber(_class); } } //"Number" is derived from "Attribute"

    [DllImport(path, CallingConvention = CallingConvention.Cdecl)]
    private static extern uint AlterAttribute(IntPtr _class, uint attribute); //This will change "Number"

    private uint attribute;
    public int Attribute
    {
      get { return (int)attribute; }
      set
      {
        if (adapter != value)
        {
          this.AlterAttribute(attribute);
        }
      }
    }

    private void AlterAttribute(uint attribute)
    {
      AlterAttribute(_class, attribute)
    }
  }

  [ViewModel(typeof(MyModel))]
  public partial class MyViewModel
  {
    partial void OnInitialize()
    {
      Model = new MyModel();
    }
  }
```
I'm looking for ``` OnPropertyChanged("Number"); ``` in the ```public int Attribute``` setter of the MyViewModel boiler plate code.

I tried placing ```[PropertyInvalidate(nameof(Attribute))]``` above the ```Number``` property in the model but that didn't do anything.

**Comment by thomasclaudiushuber** [comment]
Thanks @ideonella . Right now PropertyInvalidate is supported for readonly properties that you create in the ViewModel, like for example a FullName property like described in the docs in this repo. It is not supported when you use a Model like in your case.

But the question here is: Is using a Model the right approach? Why don't you just create a ViewModel class that has the properties Number and Attribute?

**Comment by ideonella** [comment]
I've changed my design a bit after reviewing more on MVVM and seeing some other design patterns. I think you're correct in questioning whether a model is the correct approach for what I've done, but I haven't been convinced a ViewModel is the way to do this.

It's reasonable to close this one and as I continue to build my application I'll find an implementation that is coherent.

**Comment by thomasclaudiushuber** [comment]
Thank you @ideonella! If you have any questions or if something is not clear, feel free to ping me here.
