### ISSUE TITLE
Attribute ViewModelGenerateFactory ignores IEventAggregator ConstructorArgument

### ISSUE THREAD

**Issue by Daimonion1980** [thomasclaudiushuber/mvvmgen#44]
When using attribute ViewModelGenerateFactory together with IEventSubscriber<SampleEvent> mvvmgen does not add the IEventAggregator constructor argument to the factory class.

Sample ViewModel code 

```C#
using SampleApp.Events;
using MvvmGen;
using MvvmGen.Events;
using System;

namespace SampleApp.ViewModel
{
    [ViewModelGenerateFactory]
    [ViewModel]
    public partial class SampleViewModel : IEventSubscriber<SampleEvent>
    {
        public void OnEvent(SampleEvent eventData)
        {
            throw new NotImplementedException();
        }
    }
}
```

The generated code looks as follows:

```C#
//   Generator version: 1.1.5
// </auto-generated>
using MvvmGen.Commands;
using MvvmGen.Events;
using MvvmGen.ViewModels;

namespace SampleApp.ViewModel
{
    partial class SampleViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {
        public SampleViewModel(MvvmGen.Events.IEventAggregator eventAggregator)
        {
            eventAggregator.RegisterSubscriber(this);
            this.OnInitialize();
        }

        partial void OnInitialize();
    }

    public interface ISampleViewModelFactory : IViewModelFactory<SampleViewModel> { }

    public class SampleViewModelFactory : ISampleViewModelFactory
    {
        public SampleViewModelFactory()
        {
        }

        public SampleViewModel Create() => new SampleViewModel();
    }
}
```

As you can see the factory tries to call an empty constructor, whereas the constructor needs the IEventAggregator to register the event he inherits with IEventSubscriber.

**Comment by Daimonion1980** [comment]
Temporary workaround for this issue will be to inject the IEventAggregator manually:
```C#
using SampleApp.Events;
using MvvmGen;
using MvvmGen.Events;
using System;

namespace SampleApp.ViewModel
{
    [Inject(typeof(IEventAggregator))]
    [ViewModelGenerateFactory]
    [ViewModel]
    public partial class SampleViewModel : IEventSubscriber<SampleEvent>
    {
        public void OnEvent(SampleEvent eventData)
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by Daimonion1980** [comment]
Proposal Solution https://github.com/thomasclaudiushuber/mvvmgen/commit/6259314d2f70fe1ccac9b0bc9a4df9e7296e1473

Actaully the proposal is not tested, because I don't have the time right now to setup mvvmgen build pipeline to use the new buold in my project or to read into the testsetup.

**Comment by thomasclaudiushuber** [comment]
Thank you @Daimonion1980. 

I'm out this week, will take a look at it when it comes to the end of November. On another thread, I also owe you a validation sample. That will come as well.

**Comment by thomasclaudiushuber** [comment]
Thank you @Daimonion1980 for reporting this. Will be part of the next release.
