### ISSUE TITLE
Feature Request: ViewModelFactory Create() method should be able to return interface to ViewModel it creates

### ISSUE THREAD

**Issue by Daimonion1980** [thomasclaudiushuber/mvvmgen#48]
In my application I'm using an ObservableCollection inside a ViewModel class to host a various amount of another ViewModel instances like it is implemented in EmployeeManager in MainViewModel.cs. To explain the purpose of this request I will use the names from EmployeeManager.

Mvvmgen generates a factory to EmployeeViewModel, the EmployeeViewModelFactory, and its method Create() returns a new instance of EmployeeViewModel via this attributes:

```
[ViewModelGenerateFactory]
[ViewModel(typeof(Employee))]
public partial class EmployeeViewModel
{...}
```

The Factory is used to create a variable amount of EmployeeViewModel instances in the OnEvent() Method of MainViewModel.cs

```
public async void OnEvent(EmployeeNavigationSelectedEvent eventData)
{
	var employeeViewModel = EmployeeViewModels.SingleOrDefault(x => x.Id == eventData.EmployeeId);
	if (employeeViewModel is null)
	{
		employeeViewModel = EmployeeViewModelFactory.Create();
		employeeViewModel.Load(eventData.EmployeeId);
		EmployeeViewModels.Add(employeeViewModel);
		await Task.Delay(1); // Little hack for WinUI TabView. If this is not here, WinUI won't select the tab,
							 // as next statement is setting the SelectedEmployee property
	}

	SelectedEmployee = employeeViewModel;
}
```

When Unit testing the OnEvent method of MainViewModel.cs we are able to mock the factory class because it is implemented with an interface IEmployeeViewModelFactory. 
(I'm using moq as mocking framework in my application)

But to get this mock setup correctly we have to define the behaviour of the Create() method which is called inside the OnEvent() method. 
But as defined in mvvmgen the Create() method returns a instance of a concrete class (EmployeeViewModel in this case) and we are not able to mock this class because it has no interface.

So, to test the OnEvent() Method correctly it would be better that mvvmgen is able to generate a factory which returns an interface to the ViewModel (IEmployeeViewModel) it shall generate. With this we would be able to mock the following call for the Load method and we could test the specification of the OnEvent() method. 

```
var moqEmployeeViewModelFactory = new Mock<IEmployeeViewModelFactory>();
var moqEmployeeViewModel = new Mock<IEmployeeViewModel>();	//this will not work, because out of the box, this interface does not exist, but w could create it manually
moqEmployeeViewModel.Setup(m => m.Load(It.IsAny())); //Setup for Call in onEvent of MainViewModel.cs
moqEmployeeViewModelFactory.Setup(m => m.Create()).Returns(moqEmployeeViewModel.Object); //this will also not work, because Create() returns instance of EmployeeViewModel and not IEmployeeViewModel
```

So, when it would be possible to say mvvmgen that it should create an Interface to this ViewModel (maybe through [ViewModelGenerateInterface]) and when it would be possible to define the return value of the factory (maybe through [ViewModelGenerateFactory(typeof(IEmployeeViewModel)) the unit test will be possible and the Viewmodel connection (I'm looking at the ObservableCollection<EmployeeViewModel> in MainViewModel.cs) would be more modular.

**Comment by thomasclaudiushuber** [comment]
Hi @Daimonion1980 , thank you for this proposal. Makes fully sense. I will look into this and definitely provide a solution for this, so that you can test this scenario very well. I might split this request up into two parts:
1. Allow to specify the return value of the factory's Create method
2. Support generation of a ViewModel interface (I actually like your `[ViewModelGenerateInterface]` suggestion)

Timeframe will be more like end of March. Hope this works for you.

**Comment by Daimonion1980** [comment]
Awesome. Thank you for your efforts. 

Two parts was the intended way i was thinking about this problem.

**Comment by thomasclaudiushuber** [comment]
Feature implemented and merged into main branch. Will be part of the next MvvmGen release (Will come out soon, end of March 2023). When the new `ViewModelGenerateInterface` attribute is set, an interface will be generated and the generate ViewModel implements it. If the `ViewModelGenerateFactory` attribute is set as well, the interface will automatically be used in the factory as a return type.

The simple ViewModel below shows this:

```
[ViewModelGenerateInterface]
[ViewModelGenerateFactory]
[ViewModel]
public partial class EmployeeViewModel
{
}
```

By setting the new attribute like above, an interface will be generated and it will be automatically used for the factory. Generated code for the class above is this:

```
partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase, IEmployeeViewModel
{
    public EmployeeViewModel()
    {
        this.OnInitialize();
    }
    partial void OnInitialize();
}

public interface IEmployeeViewModel
{
}

public interface IEmployeeViewModelFactory : IViewModelFactory<IEmployeeViewModel> {{ }}

public class EmployeeViewModelFactory : IEmployeeViewModelFactory
{
    public EmployeeViewModelFactory()
    {
    }

    public IEmployeeViewModel Create() => new EmployeeViewModel();
}
```

The `ViewModelGenerateFactory` attribute has now also a new `ReturnType` property so support even more flexibility:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/7116546/227726743-8b7e2952-6dda-4689-be7c-37d7a3b94531.png">



Thank you @Daimonion1980
