### ISSUE TITLE
Generating properties from a model  which has a Model property fails

### ISSUE THREAD

**Issue by MartinRothschink** [thomasclaudiushuber/mvvmgen#72]
Hi Thomas,

I'm a big fan of MVVMGen and use it very often. Most of the time my ViewModels are based on an existing model class.

Today I encountered a showstopper because my model class already contains a Model property, causing a collision with the generated protected property for the Model class.

Possible solutions: the quickest would be to rename the generated internal protected property (e.g. _model instead of Model). Perfect would be to add another parameter to the ViewModelAttribute to set the internal name.

Thanks
Martin

**Comment by TopperDEL** [comment]
+1 on this

**Comment by thomasclaudiushuber** [comment]
Thank you @MartinRothschink. This sounds like a great addition and I'll look into it.

**Comment by thomasclaudiushuber** [comment]
Thank you @MartinRothschink and @TopperDEL 

Will be fixed with next release (Planned for first week of December).

New usage:
```
namespace MyCode
{
    public class Employee
    {
        public Employee (int id)
        {
            Id = id;
        }
        public int Id { get; }
        public bool IsDeveloper { get; set; }
    }

    [ViewModel(typeof(Employee), ModelPropertyName="CustomPropName")]
    public partial class EmployeeViewModel
    {
    }
}
```

Will lead to this generated code:

```
namespace MyCode
{
    partial class EmployeeViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {
        public EmployeeViewModel()
        {
            this.OnInitialize();
        }

        partial void OnInitialize();

        public int Id => CustomPropName.Id;

        public bool IsDeveloper
        {
            get => CustomPropName.IsDeveloper;
            set
            {
                if (CustomPropName.IsDeveloper != value)
                {
                    CustomPropName.IsDeveloper = value;
                    OnPropertyChanged("IsDeveloper");
                }
            }
        }

        protected MyCode.Employee CustomPropName { get; set; }
    }
}
```
