### ISSUE TITLE
Transient ViewModels with IEventSubscriber

### ISSUE THREAD

**Issue by TopperDEL** [thomasclaudiushuber/mvvmgen#73]
I'm not sure if I'm doing it wrong: I have some ViewModels that implement IEventSubscribe<MyMessage>. If the ViewModel gets added to the Dependency Container using "AddTransient" a new ViewModel-object gets created whenever requested. I think that should be fine - but the implementation of OnEvent() gets called for every generated ViewModel during runtime.
so I would have to use AddSingleton for my ViewModels - which might lead to other errors if the ViewModels are not correctly initialized every time again.

Is my understanding here wring or is this an error in MVVMGen? Should I explicitly Unsubscribe my ViewModel after use? That would mean injecting the EventAggregator into every viewmodel and unsubscribe in the destructor or something like this.

Any ideas or hints on this? Thank you!

**Comment by TopperDEL** [comment]
Hm, I now also tried to Unsubscribe my ViewModel once the view using it gets closed. But as the Closing-info gets thrown via the EventAggregator I come to the point where I am modifying the list of subscribed entities while the list is being worked on:

![image](https://github.com/thomasclaudiushuber/mvvmgen/assets/1833242/31ed42b8-2f28-4c1b-887a-03796050b573)

For me it feels correct to unsubscribe my ViewModel once the View gets closed. It should work if you create a copy from the ``_subscribersByEvent``-List (by calling ToList()). Would that be feasable?

**Comment by thomasclaudiushuber** [comment]
Hi @TopperDEL , thank you for all these details. Do you have a small repro project that shows the issue? Would be easier for me to follow up on this one.

**Comment by TopperDEL** [comment]
@thomasclaudiushuber I created a test-repo here: https://github.com/TopperDEL/MVVMGen_Issue73

But unfortunately I cannot reproduce the issue with Unregistersubscriber. But maybe you see what my problem is. It might still be wrong usage of the DI-container from my end.

If you run the sample, it calls into TestClass1 where it creates a transient ViewModel in one method, that's not referenced by myself anymore but still receives the "MyMessage"-event. So I wanted to UnregisterSubscriber after the end of it's lifetime which crashes in my app but works in the sample. This can be seen with Testclass2 where the view publishes the CloseViewMessage which unregisters the view during the processing of the events. I don't get why this works in the sample but not in my app. But maybe you now better understand what I'm trying to do.

Thank you!

**Comment by TopperDEL** [comment]
Hm, no I even don't get that error in my app anymore. That's weird. So I don't get the crash in UnregisterSubscriber which means I can clearly unregister them and the events would not be published to viewmodels not in use anymore.

Well - then I think this issue can be closed. Sorry for the confusion.

**Comment by TopperDEL** [comment]
Hm, I still get the error in certain situation. But I am not yet able to reproduce it in my sample.

Maybe you @thomasclaudiushuber have an idea looking at that stacktrace?

![image](https://github.com/thomasclaudiushuber/mvvmgen/assets/1833242/0db8d724-d971-4104-a2de-7df807542016)

I thought it might be related to going through a command, but that also works in my sample repo without that error here.

**Comment by TopperDEL** [comment]
Never mind -I found it. I was calling the ClosePopupMessage but the ViewModel of the popup to close itself was an Eventsubscriber of that event. As it got closed it also gets removed from the subscribers - unfortunately directly during processing of that event leading to the "Collection was modified"-exception.

**Comment by thomasclaudiushuber** [comment]
Hey @TopperDEL , can this be closed or do you think there's a bug I should look into?

**Comment by TopperDEL** [comment]
Sometimes I still get it, but it is not a big Deal and might be related to my app.
Cloding it.

**Comment by thomasclaudiushuber** [comment]
@TopperDEL OK. I forked your "repro-repo". Curios if I can reproduce it. But I fear I won't find time this year to look into it, but hopefully next year. Thank you, I really appreciate the feedback and discussion!
