### ISSUE TITLE
Automatic interface generation with generics not working

### ISSUE THREAD

**Issue by Telespaz** [thomasclaudiushuber/mvvmgen#74]
Hi,

using a generic method seems to be not possible when [ViewModelGenerateInterface] is used. The generated interface is wrong, compilation not possible.

Method in class:
![image](https://github.com/thomasclaudiushuber/mvvmgen/assets/139346590/45ca3180-53f8-442b-b086-390f5b709145)

Generated method in interface:
![image](https://github.com/thomasclaudiushuber/mvvmgen/assets/139346590/7ab715ab-c473-4c13-88bd-fe0a096c7f78)

**Comment by thomasclaudiushuber** [comment]
Hi Telespaz,

thank you for reporting this. I'll look into it.

**Comment by thomasclaudiushuber** [comment]
Thank you @Telespaz , will be part of the next release.
