### ISSUE TITLE
How to exclude IEnumerable Model properties from generation

### ISSUE THREAD

**Issue by alprinias** [thomasclaudiushuber/mvvmgen#76]
Hi,

I have a Client Model, which has a Name, StreetAddress etc simple properties, but it also has an 
`IEnumerable<Order> Orders {get; set;} `
property. 

When I generate my ClientViewModel by decorating it with [ViewModel(typeof(Client))], I get all the properties of the Client model, including the Orders. However, I would like instead to add by hand an` IEnumerable<OrderViewModel> Orders`. 

So the question is, what is the best way to tell the generator to include only the simple (scalar) properties in the genaration?

Best regards,
Alex

**Comment by thomasclaudiushuber** [comment]
Hi Alex,

great question. I think this would require some kind of exclusion or ignore list. Something like

```
[ViewModel(typeof(Client),IgnoredProps="Orders")]
```

I'll think a bit more about this and will bring something up in the future.

**Comment by alprinias** [comment]
Hi Thomas,

Thanks for your answer. Yes, something like that would be great. Or something like more general, like OnlyScalarProps=true.
I have included something like this in your code in the ModelMemberInspector class with the following 
`if (!propertySymbol.Type.IsValueType)
                                    continue;`
which does the trick by excluding all the IEnumerables and complex properties (eg. an Address type). But I have not included the modification for the ViewModel attribute.
Best,
Alex

**Comment by thomasclaudiushuber** [comment]
Hi Alex,

I like the valueType approach a lot. But there might be still scenarios where you want to exclude a value type property. So, I'll take the more flexible appraoch to specify the props explicitly that should be ignored.

Works with the next release like this:

```
[ViewModel(typeof(Employee),ModelPropertiesToIgnore="FirstName, Address")]
```
